version: 2
updates:
  # Enable version updates for npm (JavaScript dependencies)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "granolacowboy"
    assignees:
      - "granolacowboy"
    labels:
      - "dependencies"
      - "automated"
    # Auto-merge minor and patch updates
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "indirect"
        update-type: "version-update:semver-minor"
      - dependency-type: "indirect"
        update-type: "version-update:semver-patch"

  # Enable version updates for Cargo (Rust dependencies)
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(rust)"
      include: "scope"
    reviewers:
      - "granolacowboy"
    assignees:
      - "granolacowboy"
    labels:
      - "dependencies"
      - "rust"
      - "automated"
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "indirect"
        update-type: "version-update:semver-minor"
      - dependency-type: "indirect"
        update-type: "version-update:semver-patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "granolacowboy"
    assignees:
      - "granolacowboy"
    labels:
      - "github-actions"
      - "automated"